#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: brightness <-|+> <delta>"
    exit 1
fi

file_brightness='/sys/class/backlight/intel_backlight/brightness'
file_max='/sys/class/backlight/intel_backlight/max_brightness'
cur=$(cat "$file_brightness")
max=$(cat "$file_max")

if [ ! -w "$file_brightness" ]; then
    sudo chown bhai /sys/class/backlight/intel_backlight/brightness
fi

new=$(($cur $1 $2))
new=$(($new>$max?$max:$new))
new=$(($new<0?0:$new))
echo $new > "$file_brightness"
echo "New brightness: $new/$max."
