#!/bin/bash

sink=`pacmd stat | awk -F": " '/^Default sink name: /{print $2}'`
volume=`pacmd list-sinks | awk '/^\s+name: /{indefault = $2 == "<'$sink'>"} /^\s+volume: / && indefault {print $5; exit}'`
echo " " $volume
