#!/bin/bash

if [ -z "$1" ]
then
    ssh-keygen -t rsa -b 4096 -C ${1}
else
    ssh-keygen -t rsa -b 4096
fi

eval "$(ssh-agent -s)"
ssh-add .ssh/id_rsa
ssh-add ~/.ssh/id_rsa
xclip -sel clip < ~/.ssh/id_rsa.pub 

